// ---------- Recettes 1.18 ----------
REC_RAW.push(
["airmail","Airmail","bulles","shake","flute","none","#F2E0A0",[["rhum_ambre",30],["citron_vert",15],["sirop_miel",15],["champagne",60,"ml","top"]],"Zeste de citron vert",{c:1,v:["french75"],h:"Le cousin au rhum du French 75, publié en 1949 dans un guide de cocktails du magazine Esquire."}],
["satans_whiskers","Satan’s Whiskers","sour","shake","coupe","none","#E89A50",[["gin",20],["vermouth_rouge",20],["vermouth_dry",20],["orange",20],["grand_marnier",10],["orange_bitters",1,"d"]],"Zeste d’orange",{c:1,v:["bronx"],h:"Une recette du Savoy Cocktail Book de 1930, cousine du Bronx avec une touche de liqueur d’orange."}],
["harvey_wallbanger","Harvey Wallbanger","highball","build","highball","cubes","#F5B040",[["vodka",45],["orange",90],["galliano",15,"ml","float"]],"Rondelle d’orange",{c:1,v:["screwdriver"],h:"Un Screwdriver coiffé de Galliano, star des années 1970 en Californie."}],
["fitzgerald","Fitzgerald","sour","shake","rocks","none","#F0E2B0",[["gin",45],["citron",20],["sirop_sucre",15],["angostura",2,"d"]],"Zeste de citron",{c:1,v:["gin_sour"],h:"Un gin sour relevé d’Angostura, créé par Dale DeGroff au Rainbow Room de New York dans les années 1990."}],
["corn_oil","Corn ’n’ Oil","stirred","build","rocks","cubes","#5A3018",[["rhum_brun",60],["falernum",15],["citron_vert",5],["angostura",2,"d"]],"Quartier de citron vert",{c:1,h:"Un classique de la Barbade : rhum sombre et falernum, épicé et profond."}],
["italian_greyhound","Italian Greyhound","highball","build","highball","cubes","#F07A6A",[["vodka",45],["pamplemousse",90],["campari",15]],"Quartier de pamplemousse",{v:["greyhound","salty_dog"],n:"Le Greyhound avec une touche d’amertume italienne."}],
["affinity","Affinity","stirred","stir","coupe","none","#8A4A30",[["scotch",30],["vermouth_rouge",30],["vermouth_dry",30],["angostura",2,"d"]],"Zeste de citron",{c:1,v:["rob_roy","manhattan"],h:"Un Rob Roy « parfait », à parts égales de scotch et des deux vermouths, du début du XXe siècle."}],
["japanese_cocktail","Japanese Cocktail","stirred","stir","coupe","none","#C8843A",[["cognac",60],["orgeat",15],["angostura",2,"d"]],"Zeste de citron",{c:1,h:"Une recette de Jerry Thomas publiée en 1862, nommée en l’honneur de la première délégation japonaise venue à New York."}],
["honeymoon","Honeymoon","sour","shake","coupe","none","#E8B060",[["calvados",45],["benedictine",15],["triple_sec",10],["citron",15]],"Zeste d’orange",{c:1,v:["jack_rose","widows_kiss"],h:"Un classique des années 1910 à la pomme, servi au Brown Derby de Los Angeles."}],
["diamondback","Diamondback","stirred","stir","rocks","big","#C8A040",[["rye",45],["calvados",20],["chartreuse_jaune",20]],"Aucune",{c:1,h:"Un cocktail puissant du Lord Baltimore Hotel, publié en 1951."}],
["cameron_kick","Cameron’s Kick","sour","shake","coupe","none","#E0C080",[["scotch",30],["irish",30],["orgeat",15],["citron",15]],"Zeste de citron",{c:1,h:"Scotch et whiskey irlandais réunis, dans une recette de 1922 de Harry MacElhone."}],
["pisco_punch","Pisco Punch","sour","shake","vin","none","#F2D890",[["pisco",60],["ananas",22.5],["sirop_sucre",15],["citron",15],["clou_girofle",3,"u"],["vin_blanc",30,"ml","top"]],"Quartier d’ananas",{c:1,v:["pisco_sour"],h:"La boisson phare du Bank Exchange de San Francisco à la fin du XIXe siècle.",st:["Écrase doucement les clous de girofle avec le sirop, au fond du shaker.","Ajoute le pisco, le jus d’ananas et le jus de citron, puis beaucoup de glace.",["Secoue vigoureusement.",12],"Filtre deux fois dans un grand verre à pied.","Verse le vin blanc par-dessus et remue doucement."]}],
["dirty_shirley","Dirty Shirley","highball","build","highball","cubes","#F2A0A8",[["vodka",45],["grenadine",15,"ml","float"],["limonade",150,"ml","top"]],"Cerises",{v:["shirley_temple"],n:"La version adulte du Shirley Temple, revenue à la mode ces dernières années."}],
["spritz_peche","Spritz à la pêche","bulles","build","vin","cubes","#F5B888",[["peche",30],["prosecco",90],["eau_gazeuse",30,"ml","top"]],"Tranche de pêche",{se:[6,7,8,9],v:["aperol_spritz","bellini"]}],
["pickleback","Pickleback","shot","build","shot","none","#D8C890",[["irish",40],["saumure",30]],"Aucune",{v:["b52"],n:"Bois le whiskey, puis la saumure de cornichons juste après : le sel efface la brûlure. Surprenant et addictif."}],
["cucumber_cooler","Concombre frais","sansalcool","mbuild","highball","cubes","#D8EEC8",[["concombre",4,"u"],["citron_vert",15],["sirop_sucre",15],["menthe",6,"f"],["eau_gazeuse",120,"ml","top"]],"Ruban de concombre",{na:1,se:[6,7,8]}],
["espresso_tonic_orange","Espresso tonic à l’orange","sansalcool","build","highball","cubes","#8A5A30",[["espresso",40],["orange",30],["tonic",120]],"Zeste d’orange",{na:1,v:["espresso_tonic"],n:"Verse l’espresso en dernier, doucement, pour garder les couches."}]
);
