// ---------- ACCORDS METS ET COCKTAILS ----------
// want : ce que le plat appelle (acid, bitter, fizz, herbal, fruity, woody, spicy, sweet, cream, strong : de -1 à 1)
const DISHES=[
 {id:"fondue",e:"🫕",n:"Fondue",why:"Le fromage fondu appelle de l’acidité, de l’amertume ou des bulles pour couper le gras. Et la tradition suisse veut un petit kirsch.",want:{acid:1,bitter:.8,fizz:.8,herbal:.4,sweet:-.8,cream:-1,strong:-.2},base:["eaux"],picks:["kirsch_sour","gespritzter","williams_tonic","chasselas_spritz","suze_tonic","genepi_tonic","kirsch_of"]},
 {id:"raclette",e:"🧀",n:"Raclette",why:"Fromage, pommes de terre et charcuterie : il faut du frais, du sec et un peu d’amertume pour garder l’appétit jusqu’au bout.",want:{acid:.8,bitter:.9,fizz:.8,herbal:.5,sweet:-.8,cream:-1},base:["eaux","amer"],picks:["gespritzter","chasselas_spritz","williams_tonic","americano","jura_negroni","genepi_tonic","suze_spritz"]},
 {id:"pizza",e:"🍕",n:"Pizza",why:"Tomate, herbes et fromage s’accordent avec l’amertume et les bulles des apéritifs italiens.",want:{bitter:1,fizz:.8,herbal:.4,sweet:-.3,cream:-.8},base:["amer","gin"],picks:["aperol_spritz","americano","negroni","sbagliato","campari_spritz","gin_tonic","bicicletta"]},
 {id:"grill",e:"🍖",n:"Grillades et burger",why:"Le grillé et le fumé répondent aux spiritueux boisés, et l’acidité rafraîchit entre deux bouchées.",want:{woody:1,acid:.6,spicy:.4,strong:.4,cream:-.6},base:["whisky","agave"],picks:["old_fashioned","whisky_sour","paloma","dark_stormy","mezcal_mule","michelada","kentucky_mule"]},
 {id:"sushi",e:"🍣",n:"Sushi",why:"Le poisson cru et le riz vinaigré demandent de la délicatesse : agrumes, bulles fines, gingembre et peu de sucre.",want:{acid:.8,fizz:.9,herbal:.6,fruity:.2,sweet:-.6,strong:-.6,woody:-.6},base:["gin","vodka"],picks:["gin_tonic","french75","hugo","gimlet","whisky_highball","moscow_mule","ranch_water"]},
 {id:"mexicain",e:"🌮",n:"Mexicain",why:"Citron vert, coriandre et piment : l’agave est chez elle, avec de l’acidité et un peu de sel.",want:{acid:1,fizz:.5,spicy:.4,herbal:.4,cream:-.8},base:["agave"],picks:["margarita","paloma","tommys","michelada","ranch_water","el_diablo","batanga"]},
 {id:"curry",e:"🍛",n:"Curry et épicé",why:"Face au piment, le fruit et un peu de douceur apaisent, les bulles rafraîchissent. Les cocktails très forts, eux, attisent le feu.",want:{fruity:1,sweet:.5,fizz:.7,spicy:.3,strong:-1,bitter:-.4},base:["rhum"],picks:["mango_mule","moscow_mule","gin_gin_mule","mai_tai","pina_colada","passion_fizz","mangue_mule"]},
 {id:"mer",e:"🦐",n:"Poisson et fruits de mer",why:"L’iode aime les agrumes, les bulles et les vins secs : tout ce qui est vif et minéral.",want:{acid:1,fizz:1,herbal:.4,sweet:-.6,woody:-.8,cream:-.8},base:["gin","vodka"],picks:["french75","gimlet","white_lady","kir","hugo","vesper","gespritzter"]},
 {id:"pates",e:"🍝",n:"Pâtes et italien",why:"L’Italie à table appelle l’Italie dans le verre : amers, vermouths et bulles.",want:{bitter:.8,fizz:.6,fruity:.3,sweet:-.2},base:["amer"],picks:["negroni","americano","aperol_spritz","bellini","limoncello_spritz","hugo","sbagliato"]},
 {id:"salade",e:"🥗",n:"Salade et légumes",why:"Un repas léger et vert s’accorde avec les herbes fraîches et le concombre.",want:{herbal:1,acid:.6,fizz:.4,strong:-.5,woody:-.8,cream:-.8},base:["gin"],picks:["gin_basil_smash","southside","eastside","hugo","gin_tonic","virgin_mule","sureau_fizz"]},
 {id:"apero",e:"🫒",n:"Apéro et charcuterie",why:"Olives, jambon cru et chips ouvrent l’appétit avec des apéritifs amers et peu alcoolisés.",want:{bitter:1,fizz:.6,strong:-.6,sweet:-.4},base:["amer"],picks:["americano","aperol_spritz","vermouth_soda","adonis","bamboo","suze_tonic","negroni"]},
 {id:"fromages",e:"🍷",n:"Plateau de fromages",why:"Les fromages affinés aiment la rondeur des vins mutés, du vermouth et des whiskys.",want:{woody:.8,sweet:.4,fruity:.4,strong:.3,acid:-.3},base:["whisky","brandy"],picks:["manhattan","porto_flip","adonis","boulevardier","sherry_cobbler","vieux_carre","rob_roy"]},
 {id:"chocolat",e:"🍫",n:"Chocolat",why:"Le cacao appelle le café, le boisé des spiritueux vieillis et un peu de crème.",want:{woody:1,cream:.8,sweet:.5,strong:.3,acid:-1,fizz:-.6},base:["whisky","brandy","rhum"],picks:["espresso_martini","black_russian","brandy_alexander","rum_of","manhattan","grasshopper","irish_coffee"]},
 {id:"dessert",e:"🍓",n:"Dessert fruité",why:"Une tarte aux fruits ou une salade de fruits se marie aux bulles et aux fruits rouges.",want:{fruity:1,fizz:.8,sweet:.3,acid:.4,woody:-.6,strong:-.5},base:[],picks:["bellini","kir_royal","clover_club","bramble","mimosa","french75","framboise_lemonade"]},
 {id:"brunch",e:"🥐",n:"Brunch",why:"Le brunch a ses classiques : bulles et agrumes, ou le Bloody Mary pour les plus salés.",want:{fizz:.8,fruity:.6,acid:.4,strong:-.8},base:[],picks:["mimosa","bloody_mary","bellini","bucks_fizz","ramos","arnold_palmer","virgin_mary"]},
 {id:"asiat",e:"🥢",n:"Wok et asiatique",why:"Sauce soja, gingembre et citronnelle aiment le gingembre et les highballs légers.",want:{spicy:.6,fizz:.9,acid:.6,herbal:.4,strong:-.6,cream:-.8},base:["whisky","gin"],picks:["whisky_highball","moscow_mule","gin_gin_mule","hugo","paloma","sureau_tonic","virgin_mule"]}
];
const PAIR_WHY={acid:"L’acidité coupe le gras et réveille le palais",bitter:"L’amertume ouvre l’appétit et nettoie la bouche",fizz:"Les bulles rafraîchissent entre deux bouchées",herbal:"Les herbes apportent de la fraîcheur",fruity:"Le fruit apaise et accompagne",woody:"Le boisé répond au grillé et au cacao",spicy:"Les épices font écho au plat",sweet:"Un peu de douceur arrondit l’ensemble",cream:"Sa rondeur accompagne la gourmandise",strong:"Un spiritueux bien présent tient tête au plat",light:"Léger, il laisse le plat au premier plan",trad:"La tradition suisse à table"};
