// ---------- INGRÉDIENTS ----------
// [id, nom, catégorie, degré %, sucre g/100ml, acidité %, arômes, extra]
// arômes : f fruité, h herbacé, l floral, e épicé, w boisé, m fumé, b amer, k crémeux (0-3)
const ING_RAW = [
["gin","Gin London Dry","spirit",42,0,0,"h2f1",{col:"#DDEBEE",tip:"Le style de base : genévrier marqué, sec, polyvalent. Tanqueray, Beefeater ou Bombay Sapphire se trouvent en grande surface et font parfaitement le job pour la plupart des recettes."}],
["vodka","Vodka","spirit",40,0,0,"",{col:"#E6EEF2",tip:"Neutre par définition : inutile de viser le haut de gamme pour les cocktails. Une vodka propre, sans arôme ajouté, suffit largement."}],
["rhum_blanc","Rhum blanc","spirit",40,0,0,"f1",{col:"#EEF0EA",tip:"Pour le Daiquiri et le Mojito, prends un rhum blanc léger de style cubain ou espagnol, comme Havana Club 3 ans ou Bacardi Carta Blanca. Évite les rhums arrangés ou épicés."}],
["rhum_ambre","Rhum ambré","spirit",40,0,0,"w2f1e1",{tip:"Un rhum vieilli quelques années, pas trop sucré : Appleton Estate Signature ou Mount Gay Eclipse. Méfie-toi des rhums très sucrés (type Diplomático), qui déséquilibrent les recettes."}],
["rhum_jam","Rhum jamaïcain","spirit",43,0,0,"f3w2e1",{tip:"Le rhum « funky » distillé en alambic, très aromatique (banane, fruits mûrs). Indispensable pour un vrai Mai Tai. Appleton 12 ans en grande surface, Smith & Cross ou Hampden chez un caviste."}],
["rhum_brun","Rhum brun","spirit",40,0,0,"w3e1",{col:"#6B3A1A",tip:"Rhum noir riche, notes de mélasse et de caramel. Le Dark ’n’ Stormy officiel utilise Gosling’s Black Seal ; Myers’s ou Captain Morgan Dark font l’affaire."}],
["cachaca","Cachaça","spirit",40,0,0,"f1h1",{col:"#EEF0E4",tip:"Eau-de-vie de jus de canne brésilienne, plus végétale que le rhum. Une cachaça blanche comme Velho Barreiro ou Pitú pour la Caipirinha."}],
["tequila","Tequila blanco","spirit",40,0,0,"h2e1",{col:"#EEF0E6",tip:"Vérifie la mention « 100 % agave » : les tequilas « mixto » sont coupées avec d’autres sucres et donnent des cocktails plus durs. Espolòn, Olmeca Altos ou El Jimador."}],
["mezcal","Mezcal","spirit",44,0,0,"m3h1e1",{col:"#EDEEE2",tip:"L’agave est cuit dans des fours en terre, d’où le goût fumé. Un mezcal joven « espadín » comme Del Maguey Vida ou Montelobos est idéal en cocktail."}],
["bourbon","Bourbon","spirit",45,0,0,"w3e1",{tip:"Doux, vanillé, notes de caramel : Buffalo Trace, Maker’s Mark ou Woodford Reserve. Autour de 45 % il tient mieux la dilution dans un sour."}],
["rye","Rye whiskey","spirit",45,0,0,"w2e3",{tip:"Plus épicé et plus sec que le bourbon : c’est le whisky historique du Manhattan et du Sazerac. Rittenhouse, Bulleit Rye ou Sazerac Rye, souvent chez un caviste."}],
["scotch","Scotch blend","spirit",40,0,0,"w2",{tip:"Un blend équilibré pour les cocktails : Monkey Shoulder, Johnnie Walker Black ou Famous Grouse. Garde tes single malts pour la dégustation."}],
["islay","Scotch tourbé","spirit",46,0,0,"m3w2",{tip:"Très fumé et iodé, il s’utilise en petite touche, souvent en float. Laphroaig 10, Ardbeg 10 ou Talisker."}],
["irish","Whiskey irlandais","spirit",40,0,0,"w1f1",{tip:"Doux et léger, parfait pour l’Irish Coffee : Jameson, Bushmills ou Tullamore D.E.W."}],
["cognac","Cognac","spirit",40,0,0,"w2f2",{tip:"Un VS ou un VSOP suffit en cocktail. Pierre Ferrand 1840 est taillé pour ça ; Hennessy VS ou Rémy Martin VSOP en grande surface."}],
["calvados","Calvados","spirit",40,0,0,"f3w1",{tip:"Eau-de-vie de cidre normande. Un calvados jeune (Pays d’Auge, 3 ans) garde plus de fruit. Il remplace l’applejack américain des vieilles recettes."}],
["pisco","Pisco","spirit",40,0,0,"f2l1",{col:"#EFEEE4",tip:"Eau-de-vie de raisin du Pérou ou du Chili. Un pisco péruvien « quebranta » est le choix classique pour le Pisco Sour."}],
["kirsch","Kirsch","spirit",40,0,0,"f2",{col:"#EEEFEA",tip:"Eau-de-vie de cerises, fierté de Zoug et de Bâle-Campagne. Un kirsch AOP est sec et très parfumé : il s’utilise comme un gin, en plus fruité."}],
["williamine","Williamine","spirit",40,0,0,"f3l1",{col:"#EEEFE6",tip:"L’eau-de-vie de poire Williams du Valais, reconnaissable à son nez de poire mûre. Morand en est la référence historique."}],
["absinthe","Absinthe","spirit",55,0,0,"h3",{ref:3,col:"#CFE6C4",tip:"Née dans le Val-de-Travers et interdite en Suisse de 1910 à 2005. Une absinthe blanche (la « bleue ») du Val-de-Travers est parfaite, et une petite bouteille dure des années."}],
["triple_sec","Cointreau (triple sec)","liqueur",40,25,0,"f2",{col:"#F1EEDF",subs:["grand_marnier"],tip:"Cointreau est la référence, sec et intense. Un triple sec générique est plus sucré et moins parfumé : réduis alors un peu le sirop."}],
["grand_marnier","Grand Marnier","liqueur",40,25,0,"f2w1",{subs:["triple_sec"],tip:"Liqueur d’orange sur base de cognac, plus ronde que le Cointreau."}],
["maraschino","Liqueur de marasquin","liqueur",32,30,0,"f2l2",{ref:15,col:"#F0EFE6",tip:"Luxardo Maraschino, la bouteille habillée de paille. Rien à voir avec les cerises confites : c’est sec, floral, un peu funky. Une bouteille dure très longtemps."}],
["chartreuse","Chartreuse verte","liqueur",55,25,0,"h3e1",{ref:15,col:"#9CC43E",tip:"Liqueur de 130 plantes, faite par les moines chartreux. Chère et parfois en rupture, mais incontournable pour le Last Word. Elle se garde indéfiniment."}],
["benedictine","Bénédictine","liqueur",40,32,0,"h2e2",{ref:10,col:"#C88A2A",tip:"Liqueur de plantes au miel, plus ronde que la Chartreuse, souvent utilisée en petite touche."}],
["st_germain","Liqueur de sureau","liqueur",20,33,0,"l3f1",{col:"#F2E6A8",subs:["sirop_sureau"],tip:"St-Germain est la référence : fleur de sureau, litchi, poire. Elle remplace le sirop de sureau dans un Hugo pour une version plus alcoolisée."}],
["amaretto","Amaretto","liqueur",28,32,0,"w2k1",{col:"#B8621E",tip:"Liqueur d’amande et de noyaux d’abricot. Disaronno est partout ; Lazzaroni est un cran plus sec."}],
["kahlua","Liqueur de café","liqueur",20,40,0,"w2b1",{col:"#2A160C",tip:"Kahlúa est partout. Mr Black est beaucoup moins sucrée et plus intense en café, si tu la trouves."}],
["cassis","Crème de cassis","liqueur",16,50,0,"f3",{col:"#4A1030",tip:"Prends une crème de cassis de Dijon ou de Bourgogne riche en fruit, bien plus parfumée que les versions bon marché."}],
["creme_mure","Crème de mûre","liqueur",16,45,0,"f3",{col:"#3E1030",subs:["cassis"],tip:"Pour le Bramble : Giffard, Joseph Cartron ou Lejay. À défaut, la crème de cassis donne un résultat proche."}],
["abricot","Liqueur d’abricot","liqueur",24,30,0,"f3",{col:"#E8922E",tip:"Une liqueur riche en fruit (Giffard, Rothman & Winter). À ne pas confondre avec l’abricotine valaisanne, une eau-de-vie sèche."}],
["cerise","Liqueur de cerise","liqueur",24,30,0,"f3e1",{col:"#6A0E1A",tip:"Cherry Heering, la référence danoise, pour le Blood and Sand."}],
["peche","Liqueur de pêche","liqueur",20,30,0,"f3",{col:"#F2C290",tip:"Crème ou schnaps de pêche (Giffard, Archers), plutôt pour les cocktails festifs et fruités."}],
["creme_cacao","Crème de cacao","liqueur",24,38,0,"w2k1",{col:"#4A2A18",tip:"Blanche ou brune selon l’effet voulu : Giffard ou Bols."}],
["falernum","Falernum","liqueur",11,30,0,"e3f1",{ref:15,col:"#F0E8C8",tip:"Liqueur de la Barbade au citron vert, gingembre, clou de girofle et amande. Rare en Suisse, mais la version maison est facile (voir le labo)."}],
["campari","Campari","amaro",25,24,0,"b3f2",{col:"#C8102E",tip:"L’amer rouge par excellence, orange amère et herbes. Pas de vrai substitut, mais Martini Riserva Bitter ou Contratto Bitter s’en approchent."}],
["aperol","Aperol","amaro",11,23,0,"f3b1",{col:"#F26A1B",tip:"Plus doux, plus orange et deux fois moins alcoolisé que le Campari."}],
["fernet","Fernet-Branca","amaro",39,8,0,"b3h3",{ref:10,col:"#2A1A12",tip:"Très amer et mentholé. Une petite quantité suffit à transformer un cocktail."}],
["amaro","Amaro (Nonino, Montenegro)","amaro",30,18,0,"b2e2f1",{col:"#8A4A1E",tip:"Un amaro doux-amer. Le Paper Plane utilise l’Amaro Nonino ; Montenegro ou Averna sont plus faciles à trouver et marchent bien."}],
["appenzeller","Appenzeller Alpenbitter","amaro",29,18,0,"h3b2e1",{col:"#6A3A1A",tip:"L’amer aux 42 plantes d’Appenzell, un digestif très suisse qui se comporte en cocktail comme un amaro alpin."}],
["gentiane","Suze (gentiane)","amaro",15,15,0,"b3h2",{col:"#F0DC70",tip:"La Suze, jaune et amère, en grande surface. D’autres liqueurs de gentiane du Jura ou du Valais font aussi très bien l’affaire."}],
["vermouth_rouge","Vermouth rouge","vin",16,16,0.6,"e2h1f1",{col:"#7A1E14",tip:"Il fait la moitié d’un Negroni ou d’un Manhattan. Martini Rosso ou Cinzano pour commencer, Cocchi di Torino ou Carpano Antica pour monter d’un cran. Une fois ouvert, au frigo : il se garde environ un mois."}],
["vermouth_dry","Vermouth dry","vin",18,3,0.6,"h2",{col:"#EDEAD2",tip:"Noilly Prat ou Martini Extra Dry. Comme tout vermouth, c’est du vin : frigo après ouverture, et à finir en un à deux mois."}],
["lillet","Lillet blanc","vin",17,9.5,0.6,"f2l1",{col:"#F0DC8A",tip:"Apéritif bordelais à base de vin et d’agrumes. Au frigo après ouverture."}],
["prosecco","Prosecco","vin",11,1.5,0.6,"f1",{fizz:1,col:"#F2EDC0",tip:"Un prosecco brut, pas trop sucré, bien froid."}],
["champagne","Champagne ou crémant","vin",12,1,0.6,"f1",{fizz:1,col:"#F2E8B8",tip:"Pour un French 75 ou un Kir royal, un crémant ou un mousseux suisse fait très bien l’affaire, pour bien moins cher."}],
["vin_blanc","Vin blanc (chasselas)","vin",12,0.3,0.6,"f1l1",{col:"#F2EDC8",tip:"Un chasselas vaudois ou valaisan, léger et minéral, est parfait pour un Kir ou un spritz."}],
["vin_rouge","Vin rouge","vin",13,0.3,0.55,"f2w1",{ref:15,col:"#5A1020",tip:"Pour le float du New York Sour, un rouge fruité et peu tannique : pinot noir ou gamay."}],
["angostura","Angostura","bitters",44.7,4,0,"e3b2",{ref:1.6,col:"#6A1E10",tip:"Le bitter aromatique indispensable : cannelle, clou de girofle, gentiane. Une bouteille dure des années."}],
["orange_bitters","Bitter à l’orange","bitters",40,0,0,"f3b2",{ref:1.6,col:"#D8782A",tip:"Regans’ ou Angostura Orange. Il relève les Martinis et les cocktails au gin."}],
["peychaud","Peychaud’s Bitters","bitters",35,5,0,"l2e2f1",{ref:1.6,col:"#C8201E",tip:"Le bitter anisé et floral de La Nouvelle-Orléans, indispensable au Sazerac. Plutôt chez un caviste ou en ligne."}],
["sirop_sucre","Sirop de sucre","sirop",0,61.5,0,"",{basic:1,col:"#F4F2EA",tip:"Un volume de sucre pour un volume d’eau, mélangés jusqu’à dissolution. Deux minutes de travail, un mois au frigo."}],
["sirop_miel","Sirop de miel","sirop",0,60,0,"l1",{col:"#E8B84A",tip:"Trois parts de miel pour une part d’eau chaude. Un miel de fleurs suisse, pas trop marqué."}],
["grenadine","Grenadine","sirop",0,55,0.2,"f2",{col:"#B0102A",tip:"Évite les grenadines fluo sans grenade. La version maison au jus de grenade est incomparable (voir le labo), sinon Monin ou Giffard."}],
["orgeat","Sirop d’orgeat","sirop",0,58,0,"k2l1",{col:"#F2EEE2",tip:"Sirop d’amande à la fleur d’oranger, clé du Mai Tai. Monin ou Giffard en grande surface, ou maison."}],
["sirop_sureau","Sirop de sureau","sirop",0,60,0.3,"l3f1",{col:"#F2E8B0",subs:["st_germain"],tip:"Le sirop de fleurs de sureau suisse, partout en grande surface. Encore meilleur maison fin mai, quand le sureau fleurit."}],
["sirop_agave","Sirop d’agave","sirop",0,60,0,"",{col:"#E8C87A",tip:"Nectar d’agave dilué moitié-moitié avec de l’eau, pour une texture proche d’un sirop de sucre."}],
["sirop_gingembre","Sirop de gingembre","sirop",0,55,0,"e3",{col:"#EED890",tip:"Plus facile à faire maison qu’à trouver : jus de gingembre frais et sucre à parts égales."}],
["sirop_framboise","Sirop de framboise","sirop",0,60,0.3,"f3",{col:"#C0183A",tip:"Un sirop riche en fruit, comme ceux de Morand ou de Monin."}],
["sirop_passion","Sirop de fruit de la passion","sirop",0,55,0.5,"f3",{col:"#F0B030",tip:"Monin ou Giffard. Un sirop maison à la pulpe de fruits frais est bien plus vif."}],
["sirop_vanille","Sirop de vanille","sirop",0,60,0,"k2",{col:"#EED8A8",tip:"Monin, ou maison avec une gousse fendue dans un sirop de sucre."}],
["citron_vert","Citron vert","jus",0,1.6,6,"f1",{subs:["citron"],tip:"Toujours pressé à la minute : un jus en bouteille change tout le cocktail."}],
["citron","Citron jaune","jus",0,2.5,6,"f1",{subs:["citron_vert"],tip:"Pressé frais, idéalement le jour même."}],
["orange","Jus d’orange","jus",0,9,0.8,"f2",{}],
["pamplemousse","Jus de pamplemousse","jus",0,7,2.4,"f2b1",{}],
["ananas","Jus d’ananas","jus",0,10,0.8,"f3",{}],
["canneberge","Jus de canneberge","jus",0,13,0.6,"f2",{}],
["pomme","Jus de pomme","jus",0,10,0.5,"f2",{tip:"Un jus de pomme suisse trouble (Süssmost) a beaucoup plus de goût qu’un jus filtré."}],
["tomate","Jus de tomate","jus",0,3,0.4,"h1",{}],
["espresso","Espresso","frais",0,0,0.2,"w2b2",{}],
["cafe","Café chaud","frais",0,0,0.1,"w1b1",{}],
["eau_gazeuse","Eau gazeuse","soft",0,0,0,"",{fizz:1}],
["tonic","Tonic","soft",0,8.5,0.3,"b1",{fizz:1,tip:"Un tonic de qualité change tout : Fever-Tree ou Thomas Henry plutôt que les tonics très sucrés."}],
["ginger_beer","Ginger beer","soft",0,10,0.2,"e3",{fizz:1,tip:"Plus piquante que le ginger ale : Fever-Tree, Thomas Henry ou Goslings."}],
["ginger_ale","Ginger ale","soft",0,9,0.2,"e1",{fizz:1}],
["cola","Cola","soft",0,10.6,0.15,"e1",{fizz:1}],
["rivella","Rivella rouge","soft",0,9,0.3,"f1h1",{fizz:1}],
["soda_pamplemousse","Limonade au pamplemousse","soft",0,9,0.5,"f2b1",{fizz:1}],
["menthe","Menthe fraîche","frais",0,0,0,"h3",{}],
["basilic","Basilic frais","frais",0,0,0,"h3",{}],
["blanc_oeuf","Blanc d’œuf","frais",0,0,0,"k2",{}],
["creme","Crème entière","frais",0,3,0,"k3",{}],
["creme_coco","Crème de coco","frais",0,45,0,"k3f1",{tip:"La crème de coco sucrée (type Coco López), pas le lait de coco. Si tu ne trouves que du lait de coco, mélange-le avec autant de sirop de sucre."}],
["fleur_oranger","Eau de fleur d’oranger","frais",0,0,0,"l3",{ref:1}],
["marmelade","Marmelade d’orange","frais",0,60,0.5,"f3b1",{}],
["worcestershire","Sauce Worcestershire","frais",0,10,0.5,"e2",{ref:1.6}],
["tabasco","Tabasco","frais",0,0,1,"e3",{ref:1}],
["sucre","Morceau de sucre","frais",0,0,0,"",{basic:1}],
["eau","Eau glacée","frais",0,0,0,"",{basic:1}]
];

const CATS = {
  spirit:{n:"Spiritueux",track:1},
  liqueur:{n:"Liqueurs",track:1},
  amaro:{n:"Amers & apéritifs",track:1},
  vin:{n:"Vermouths & vins",track:1},
  bitters:{n:"Bitters",track:1},
  sirop:{n:"Sirops",track:1},
  jus:{n:"Agrumes & jus",track:0},
  soft:{n:"Softs & bulles",track:0},
  frais:{n:"Frais & épicerie",track:0}
};
