const fs=require('fs');const h=fs.readFileSync('dist/zeste.html','utf8');let js=h.split('<script>')[1].split('</script>')[0];
global.document={querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){},createElement:()=>({style:{setProperty(){}},classList:{add(){},remove(){},toggle(){}},setAttribute(){},appendChild(){}}),getElementById:()=>null,body:{appendChild(){},prepend(){},classList:{add(){},remove(){},toggle(){}}},documentElement:{dataset:{}}};global.localStorage={getItem:()=>null,setItem(){}};global.window={addEventListener(){}};global.setInterval=()=>0;global.setTimeout=()=>0;global.requestAnimationFrame=()=>0;global.matchMedia=()=>({matches:false,addEventListener(){}});
js=js.replace(/\ninit\(\);[\s\S]*$/,'\n'); eval(js+`REC_RAW.forEach(r=>{ if(r[9]&&r[9].n){ r[9].tip=r[9].n; delete r[9].n; } }); buildRecipes([]);
const IBA=JSON.parse(fs.readFileSync('data/iba.json','utf8')).cocktails; const pairs=JSON.parse(fs.readFileSync('data/ibapairs.json','utf8')); pairs.push(["South Side","southside"]);
const RULES=[[/lime juice|fresh lime$|squeezed lime/,"citron_vert"],[/lemon juice|squeezed lemon/,"citron"],[/orange juice/,"orange"],[/grapefruit juice/,"pamplemousse"],[/grapefruit soda/,"soda_pamplemousse"],[/pineapple juice/,"ananas"],[/cranberry/,"canneberge"],[/tomato/,"tomate"],
[/demerara sugar syrup|sugar syrup|simple syrup/,"sirop_sucre"],[/honey/,"sirop_miel"],[/orgeat/,"orgeat"],[/grenadine/,"grenadine"],[/falernum/,"falernum"],[/raspberry syrup/,"sirop_framboise"],[/white peach puree|peach puree/,"peche_puree"],[/passion fruit (syrup|puree)/,"sirop_passion"],[/agave nectar/,"sirop_agave"],
[/egg white/,"blanc_oeuf"],[/egg yolk/,"oeuf"],[/coconut cream/,"creme_coco"],[/crème de cacao|creme de cacao/,"creme_cacao"],[/crème de menthe|creme de menthe/,"creme_menthe"],[/violette/,"violette"],[/cassis/,"cassis"],[/mûre|mure/,"creme_mure"],[/fresh cream|^cream$/,"creme"],
[/soda water/,"eau_gazeuse"],[/ginger beer/,"ginger_beer"],[/ginger ale/,"ginger_ale"],[/cola/,"cola"],[/tonic/,"tonic"],[/champagne|sparkling wine/,"champagne"],[/prosecco/,"prosecco"],[/dry white wine/,"vin_blanc"],[/red wine/,"vin_rouge"],[/port/,"porto"],[/sherry|palo cortado|amontillado/,"sherry"],
[/dry vermouth/,"vermouth_dry"],[/sweet (red )?vermouth/,"vermouth_rouge"],[/lillet/,"lillet"],[/campari/,"campari"],[/aperol/,"aperol"],[/cynar/,"cynar"],[/fernet/,"fernet"],[/amaro nonino/,"amaro"],
[/cointreau|triple sec/,"triple_sec"],[/grand marnier/,"grand_marnier"],[/curacao/,"curacao"],[/maraschino/,"maraschino"],[/green chartreuse/,"chartreuse"],[/yellow chartreuse/,"chartreuse_jaune"],[/bénédictine|benedictine/,"benedictine"],[/drambuie/,"drambuie"],[/amaretto/,"amaretto"],[/kahl|coffee liqueur/,"kahlua"],[/apricot brandy/,"abricot"],[/peach schnapps/,"peche"],[/cherry brandy|cherry sangue/,"cerise"],[/raspberry liqueur/,"framboise_liq"],[/passion fruit liqueur/,"passoa"],[/frangelico/,"frangelico"],[/elderflower/,"sirop_sureau"],
[/vodka/,"vodka"],[/tequila/,"tequila"],[/mezcal/,"mezcal"],[/pisco/,"pisco"],[/cacha/,"cachaca"],[/agricole|martinique/,"rhum_agricole"],[/rum|\bron\b|aguardiente/,"RHUM"],[/bourbon/,"bourbon"],[/rye/,"rye"],[/scotch|lagavulin/,"scotch"],[/irish whiskey/,"irish"],[/calvados/,"calvados"],[/cognac|brandy/,"cognac"],[/grappa/,"grappa"],[/absinthe|pernod/,"absinthe"],[/gin/,"gin"],
[/peychaud/,"peychaud"],[/orange bitters/,"orange_bitters"],[/angostura|aromatic bitters/,"angostura"],[/mint/,"menthe"],[/basil/,"basilic"],[/sugar/,"sucre"],[/espresso/,"espresso"],[/coffee/,"cafe"],[/worcestershire/,"worcestershire"],[/tabasco/,"tabasco"],[/orange flower/,"fleur_oranger"],[/vanilla/,"vanille"],[/^water$|plain water/,"eau"],[/salt/,"sel"],[/lime cut|fresh lime/,"citron_vert"]];
const grp=id=>{ if(!id) return id; if(/^rhum|RHUM/.test(id)) return "RHUM"; if(["champagne","prosecco","cremant"].includes(id)) return "BULLES"; if(["sirop_sucre","sucre","sirop_canne"].includes(id)) return "SUCRE"; if(["cognac","brandy","armagnac"].includes(id)) return "COGNAC"; if(["triple_sec","curacao"].includes(id)) return "ORANGE"; if(["bourbon","rye","whisky"].includes(id)) return "WHISKEYUS"; if(["espresso","cafe"].includes(id)) return "CAFE"; if(["creme_cacao","creme_cacao_blanc"].includes(id)) return "CACAO"; return id; };
const parse=s=>{ const t=s.toLowerCase().trim(); let q=null,u="ml"; let m=t.match(/^([\\d.,]+)\\s*(ml|cl)\\b\\s*(.*)$/); if(m){ q=parseFloat(m[1].replace(",","."))*(m[2]==="cl"?10:1); return {q,u,name:m[3]}; }
  m=t.match(/^([\\d.,]+)\\s*(dash(?:es)?|drops?)\\s*(?:of\\s+)?(.*)$/); if(m) return {q:parseFloat(m[1]),u:"d",name:m[3]};
  m=t.match(/^([\\d.,]+)\\s*(bar ?spoons?|tsp|teaspoons?)\\s*(?:of\\s+)?(.*)$/); if(m) return {q:parseFloat(m[1])*5,u:"ml",name:m[3]};
  m=t.match(/^([\\d.,]+)\\s*(.*)$/); if(m) return {q:parseFloat(m[1]),u:"u",name:m[2]}; return {q:null,u:"?",name:t}; };
const mapI=n=>{ for(const [re,id] of RULES) if(re.test(n)) return id; return "?"+n; };
const glassOf=s=>{ s=s.toLowerCase(); if(/copper mug/.test(s)) return "mug"; if(/flute|champagne glass/.test(s)) return "flute"; if(/wine glass|balloon/.test(s)) return "vin"; if(/highball|collins|tall glass|hurricane/.test(s)) return "highball"; if(/old fashioned|rocks|tumbler/.test(s)) return "rocks"; if(/irish coffee|warm glass|coffee glass|mug/.test(s)) return "tasse"; if(/cocktail glass|martini glass|coupe|nick/.test(s)) return "coupe"; if(/shot/.test(s)) return "shot"; return null; };
const methOf=s=>{ s=s.toLowerCase(); if(/blend/.test(s)) return "blend"; if(/shake/.test(s)) return "shake"; if(/stir/.test(s)&&/mixing glass|strain/.test(s)) return "stir"; if(/muddle/.test(s)) return "mbuild"; return "build"; };
const report=[];
pairs.forEach(([t,id])=>{ const c=IBA.find(x=>x.title===t), r=RMAP[id]; if(!c||!r) return; const issues=[];
  const ib=c.ingredients.map(parse).map(x=>Object.assign(x,{id:mapI(x.name)}));
  ib.forEach(x=>{ if(/optional/.test(x.name)) return; const mine=r.ing.find(i=>grp(i.id)===grp(x.id));
    if(!mine){ if(!/^(sel|eau)$/.test(x.id)) issues.push("MANQUE "+x.id+" ("+(x.q??"")+" "+x.u+")"); return; }
    if(x.u==="ml"&&x.q!=null&&(mine.u||"ml")==="ml"){ const d=mine.q-x.q; if(Math.abs(d)>Math.max(5,x.q*0.2)) issues.push("DOSE "+mine.id+" : Zeste "+mine.q+" / IBA "+x.q); }
    if(x.u==="d"&&mine.u==="d"&&Math.abs(mine.q-x.q)>=2) issues.push("TRAITS "+mine.id+" : Zeste "+mine.q+" / IBA "+x.q); });
  r.ing.forEach(i=>{ if(i.r==="opt"||ING[i.id].basic&&["sucre","eau"].includes(i.id)) return; if(!ib.some(x=>grp(x.id)===grp(i.id))) issues.push("EN TROP "+i.id+" ("+i.q+")"); });
  const g=glassOf(c.method+" "+(c.garnish||"")), gm={coupe:["coupe","martini"],rocks:["rocks"],highball:["highball"],flute:["flute"],vin:["vin"],mug:["mug"],tasse:["tasse"],shot:["shot"]};
  if(g&&!(gm[g]||[]).includes(r.g)) issues.push("VERRE Zeste "+r.g+" / IBA "+g);
  const m=methOf(c.method); const mm={shake:["shake","mshake"],stir:["stir"],build:["build","mbuild","hot"],mbuild:["mbuild","mshake"],blend:["shake","blend"]}; if(!(mm[m]||[]).includes(r.m)) issues.push("MÉTHODE Zeste "+r.m+" / IBA "+m);
  report.push({t,id,issues,iba:c.ingredients.join(" ; "),g:c.garnish,url:c.url,mine:r.ing.map(i=>i.id+" "+i.q+(i.u&&i.u!=="ml"?i.u:"")).join(" ; "),gar:r.gar,gl:r.g,m:r.m}); });
fs.writeFileSync('data/ibareport.json',JSON.stringify(report,null,1));
const bad=report.filter(x=>x.issues.length); console.log("recettes comparées :",report.length,"| conformes :",report.length-bad.length,"| à examiner :",bad.length);
const cnt={}; bad.forEach(x=>x.issues.forEach(i=>{ const k=i.split(" ")[0]; cnt[k]=(cnt[k]||0)+1; })); console.log(cnt);`);
